development: &default
  adapter: postgresql
  encoding: unicode
  database: notes_development
  pool: 5
  host: localhost

test: &default
  adapter: postgresql
  encoding: unicode
  database: notes_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: notes
  pool: 5
  username: postgres
  password: